version: 2
jobs:
  build:
    macos:
      xcode: "10.1.0"

    steps:
      - checkout

      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_SCHEME: Tests

      - store_test_results:
          path: test_output
 
      - store_artifacts:
          path: test_output
      
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
